# umbrella-app.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umbrella-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/srvgit/autoapi-k8.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
