apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-api-graphlet
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: auto-api-graphlet
        image: docker1460/autoapi:latest
        env:
        - name: ENVIRONMENT
          value: dev
