apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: user-graphlet-vpa
spec:
  updatePolicy:
    updateMode: "Off"  # In dev, don't auto-update, just provide recommendations
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        maxAllowed:
          cpu: "2"
          memory: "2Gi"
        minAllowed:
          cpu: "100m"
          memory: "100Mi"
