apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base

patches:
  - path: patch-deployment.yml
  - path: patch-service.yml
  - path: patch-hpa.yml
  - path: patch-hpa.yml


commonLabels:
  app: user-api-graphlet
