apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-graphlet
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: graphlet
        image: user-graphlet-image:v1-dev
        env:
        - name: ENVIRONMENT
          value: dev
