apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: generic-graphlet-vpa
spec:
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        maxAllowed:
          cpu: 1
          memory: 1Gi
        minAllowed:
          cpu: "100m"
          memory: 100Mi
