apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../../base

patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
  - path: patch-hpa.yaml


commonLabels:
  app: user-graphlet
