apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-graphlet
  labels:
    app: graphlet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphlet
  template:
    metadata:
      labels:
        app: graphlet
    spec:
      containers:
      - name: graphlet
        image: generic-graphlet-image:v1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
