apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-graphlet
  labels:
    app: graphlet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphlet
  template:
    metadata:
      labels:
        app: graphlet
    spec:
      containers:
      - name: graphlet
        image: docker1460/autoapi
        ports:
        - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 10
      imagePullSecrets:
      - name: regcred

        
