apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: generic-graphlet-vpa
  labels:
    app: graphlet
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       generic-graphlet
  updatePolicy:
    updateMode: "Auto"
