apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vehicleService
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/srvgit/autoapi-k8.git
    targetRevision: HEAD
    path: overlays/vehicleService/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true